"""Cron script installer.

Generates a self-contained dream-cycle entry script in ~/.hermes/scripts/
(where Hermes requires cron scripts to live) and returns its relative name.

The generated script is run by Hermes' own Python (sys.executable) in a
``no_agent`` cron job: it bootstraps sys.path to find Zellandine, loads the
Hermes .env for provider credentials, runs the cycle, and prints the digest
to stdout — which Hermes delivers verbatim (e.g. to Telegram).
"""
from __future__ import annotations

from pathlib import Path

from . import hermes_api

SCRIPT_NAME = "zellandine_dream.py"


def _src_root() -> Path:
    # this file is <src>/zellandine/install.py → src root is parents[1]
    return Path(__file__).resolve().parents[1]


def cron_script_body() -> str:
    src = _src_root()
    return f'''#!/usr/bin/env python3
"""Zellandine nightly dream cycle — Hermes cron entry (auto-generated).

Generated by `zellandine install-cron`. Safe to regenerate.
Runs collect→consolidate→prune→synthesize→report and prints the digest.
Stages proposals into an artifact; never mutates Alfred's live state.
"""
import os
import sys
from pathlib import Path

# 1) Make Zellandine importable (installed-package-free).
sys.path.insert(0, {str(src)!r})

# 2) Load Hermes .env so the LLM provider has its API key.
_env = Path.home() / ".hermes" / ".env"
if _env.exists():
    import re
    for _line in _env.read_text(encoding="utf-8", errors="replace").splitlines():
        _m = re.match(r"\\s*(?:export\\s+)?([A-Z0-9_]+)\\s*=\\s*(.*)\\s*$", _line)
        if _m and _m.group(1) not in os.environ:
            os.environ[_m.group(1)] = _m.group(2).strip().strip('"').strip("'")

from zellandine.config import load_config
from zellandine.run import run_cycle


def main() -> int:
    cfg = load_config()
    dry = cfg.apply_mode == "dry-run"
    summary = run_cycle(config=cfg, depth=cfg.depth, dry_run=dry)
    # Hermes delivers stdout verbatim; empty stdout = silent.
    if summary["proposal_count"] == 0 and summary["insight_count"] == 0:
        print("[SILENT]")
        return 0
    print(summary["digest"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def ensure_cron_script() -> str:
    """Write the cron entry script into ~/.hermes/scripts/. Returns its name."""
    scripts_dir = hermes_api.hermes_home() / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    target = scripts_dir / SCRIPT_NAME
    target.write_text(cron_script_body(), encoding="utf-8")
    target.chmod(0o755)
    return SCRIPT_NAME
